# Generated by Django 5.1.4 on 2024-12-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(db_index=True, null=True, unique=True, verbose_name='ID Telegram')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Юзернейм')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('datetime_join', models.DateTimeField(blank=True, null=True, verbose_name='Время регистрации')),
                ('datetime_update', models.DateTimeField(blank=True, null=True, verbose_name='Время последней активности')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
    ]
